name = "mayhem"
main = "server/worker.js"
compatibility_date = "2025-01-01"
workers_dev = true
pages_build_output_dir = "dist"

[vars]
ROOM_NAME = "global"

[[durable_objects.bindings]]
name = "GLOBAL_ARENA"
class_name = "GlobalArenaRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GlobalArenaRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PrivateRoomLobbyHub"]

[[migrations]]
tag = "v3"
deleted_classes = ["PrivateRoomLobbyHub"]
