ALTER TABLE profiles ADD COLUMN profile_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN headline TEXT;
ALTER TABLE profiles ADD COLUMN bio TEXT;
ALTER TABLE profiles ADD COLUMN updated_at INTEGER NOT NULL DEFAULT 0;
