export function toEntityState(entity) {
  return {
    id: entity.id,
    kind: entity.kind,
    username: entity.username,
    classId: entity.classId,
    x: Number(entity.x.toFixed(3)),
    y: Number((entity.y || 1.6).toFixed(3)),
    z: Number(entity.z.toFixed(3)),
    yaw: Number((entity.yaw || 0).toFixed(4)),
    pitch: Number((entity.pitch || 0).toFixed(4)),
    weaponId: entity.weaponId || 'rifle',
    moveSpeedNorm: Number((entity.moveSpeedNorm || 0).toFixed(3)),
    sprinting: !!entity.sprinting,
    hp: Number(entity.hp.toFixed(2)),
    hpMax: Number(entity.hpMax.toFixed(2)),
    armor: Number(entity.armor.toFixed(2)),
    armorMax: Number(entity.armorMax.toFixed(2)),
    kills: Math.max(0, Number(entity.kills || 0)),
    deaths: Math.max(0, Number(entity.deaths || 0)),
    progressScore: Number((entity.progressScore || 0).toFixed(3)),
    teamId: entity.teamId || '',
    wallhackRadius: entity.wallhackRadius,
    alive: !!entity.alive,
    spawnShieldUntil: entity.spawnShieldUntil || 0,
    streamHeat: Number((entity.streamHeat || 0).toFixed(3)),
    streamOverheatedUntil: entity.streamOverheatedUntil || 0,
    muzzleFlashUntil: entity.muzzleFlashUntil || 0,
    stunUntil: entity.stunUntil || 0,
    slowUntil: entity.slowUntil || 0,
    visibleWallhack: true
  };
}
